// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	invoiceEntity "TiBO_API/businesses/invoiceEntity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, invoiceData
func (_m *Repository) Create(ctx context.Context, invoiceData *invoiceEntity.Domain) (invoiceEntity.Domain, error) {
	ret := _m.Called(ctx, invoiceData)

	var r0 invoiceEntity.Domain
	if rf, ok := ret.Get(0).(func(context.Context, *invoiceEntity.Domain) invoiceEntity.Domain); ok {
		r0 = rf(ctx, invoiceData)
	} else {
		r0 = ret.Get(0).(invoiceEntity.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *invoiceEntity.Domain) error); ok {
		r1 = rf(ctx, invoiceData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userId
func (_m *Repository) GetByUserID(ctx context.Context, userId string) ([]invoiceEntity.Domain, error) {
	ret := _m.Called(ctx, userId)

	var r0 []invoiceEntity.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []invoiceEntity.Domain); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]invoiceEntity.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields: ctx, ID
func (_m *Repository) GetID(ctx context.Context, ID uint) ([]invoiceEntity.Domain, error) {
	ret := _m.Called(ctx, ID)

	var r0 []invoiceEntity.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) []invoiceEntity.Domain); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]invoiceEntity.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
