name: on-push-master

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
      - 'development'
      - 'unit-testing'
      - 'feature/*'

jobs:
  api-test:
    name: api test - run unitest on action
    runs-on: ubuntu-latest
    container: golang:1.17
    services:
      mysql:
        image: mysql:latest
        env:
#          MYSQL_ROOT_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_USER: ${DB_HOST_DOCKER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME_TESTING}
        ports:
          - 3305:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v2
      - name: running unitest
        env:
          DB_HOST: dockerDB
          DB_PORT: 8000
          DB_PASS: root
          DB_NAME: tibo_database_test
        run: |
          go mod tidy
          go test ./... -cover -failfast
